M48
; DRILL file KiCad 10.0.5 date 2026-09-27T21:25:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-27T21:25:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X151.555Y-22.255
X156.555Y-22.255
T2
X134.095Y-35.15
X134.095Y-38.15
T3
X89.0Y-22.0
X108.0Y-22.0
X191.0Y-22.0
X210.0Y-22.0
T4
X51.1Y-22.1
X51.1Y-115.1
X277.1Y-22.1
X277.1Y-115.1
M30
